### ISSUE TITLE
Erroneous request made to package.lterent.edu during ORCID authentication process

### ISSUE THREAD

**Issue by servilla** [PASTAplus/DataPortal#58]
When logging into PASTA via the ORCID OAuth2 interface, an erroneous request to package.lternet.edu is made with the ORCID identifier. The following log entry is from pasta.lternet.edu and shows a 404 response for the erroneous request from package.lternet.edu (the request originates from portal.edirepository.org):

> 129.24.240.161 - - [02/Sep/2021:20:11:51 -0600] "GET /package/user/https://orcid.org/0000-0002-3192-7306 HTTP/1.1" 404 0 "-" "Apache-HttpClient/4.3.3 (java 1.5)"

This error has been reported recently and log entries do show multiple occurrences, although I have not been able to recreate beyond its first occurrence for me.

**Comment by servilla** [comment]
Login sequence on portal.edirepository.org (nothing private):

> 2021-09-02 20:11:51.039 [INFO] [edu.lternet.pasta.portal.LoginServlet]: https://orcid.org/0000-0002-3192-7306*https://pasta.edirepository.org/authentication*1630663910894*authenticated 
2021-09-02 20:11:51.039 [INFO] [edu.lternet.pasta.portal.LoginServlet]: https://orcid.org/0000-0002-3192-7306 
2021-09-02 20:11:51.039 [INFO] [edu.lternet.pasta.portal.LoginServlet]: https://pasta.edirepository.org/authentication 
2021-09-02 20:11:51.039 [INFO] [edu.lternet.pasta.portal.LoginServlet]: 1630663910894 
2021-09-02 20:11:51.040 [INFO] [edu.lternet.pasta.portal.LoginServlet]: authenticated 
2021-09-02 20:11:51.040 [INFO] [edu.lternet.pasta.portal.LoginServlet]: NmnHOm4VduywcqPCs4jRLL3XJJsZNWUu+3Zt6bKTAQRQ+jVKkmGFPmqYsrCpC8saTvXoouPEaWSIr9ImCh3KbxDZAFvc/H/EqSf95vivnJyN4w0+SUsMtXsWy
em3w8N9zq4vcYhdiiCxeuIDuEISiS1HmQCuynXqNh+tGXglY7kBuXBCAMPvkU0AaXa5I9lZI4BbhzTFOEeR4J67ekDzDZYDCOSHTwZzHPhKthmR9DVSCIloC3aCPI3RCoPyeu9g9QF4B5BILATJiv1xxf888hhxR6/w9rppa4BidQfJaJ6kScGjS1Qg/KrSUd
LZZQ827P9LplEWY4DJSNXdgNma/Q== 
2021-09-02 20:11:51.219 [ERROR] [edu.lternet.pasta.portal.UserBrowseServlet]: edu.lternet.pasta.common.ResourceNotFoundException: PASTA returned status code 404 -  
edu.lternet.pasta.common.ResourceNotFoundException: PASTA returned status code 404 - 
        at edu.lternet.pasta.client.PastaClient.handleStatusCode(PastaClient.java:303)
        at edu.lternet.pasta.client.DataPackageManagerClient.listUserDataPackages(DataPackageManagerClient.java:1092)
        at edu.lternet.pasta.portal.UserBrowseServlet.doPost(UserBrowseServlet.java:129)
        at edu.lternet.pasta.portal.UserBrowseServlet.doGet(UserBrowseServlet.java:86)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at edu.lternet.pasta.portal.bots.BotsFilter.doFilter(BotsFilter.java:112)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by servilla** [comment]
This error seems to occur if the user attempts to access the userBrowseServlet webpage without authenticating. This results in the system requiring authentication, followed by a redirect back to the userBrowseServlet, where the error occurs. Upon return to the userBrowseServlet, the servlet must send the erroneous request onto package.lternet.edu. To recreate:

1. https://portal.edirepository.org/nis/userBrowseServlet
2. Perform authentication with ORCID
3. Redirect back to userBrowseServlet results in the error

**Comment by servilla** [comment]
Note this error occurs with both GitHub and ORCID OAuth2 authentication user identifiers, but not the Google OAutho2 user identifier.

**Comment by servilla** [comment]
Both ORCID and GitHub user identifiers begin with `https://`:
ORCID: `https://orcid.org/0000-0002-3192-7306`
GitHub: `https://github.com/servilla`
